export const VpSalesAndMarketingTemplated = {
    getFormName() {
        return {
            from_date: '',
            year_goal: '',
            check_in_how_are_you_doing: '',
            what_can_i_do_to_support_you: '',

            annual_deliveables: [{
                title: '',
                description: ''
            }],
            primary_task: [{
                title: '',
                due_date: '',
                actual_date_completed: '',
                comments: '',
            }],
            secondary_task: [{
                title: '',
                due_date: '',
                actual_date_completed: '',
                comments: '',
            }],
            any_addtional_topic: [{
                title: '',
                comments: '',
            }],
            goals_for_the_week: [{
                title: '',
                status_1: '',
                status_2: '',
                reason_1: '',
                reason_2: '',
            }],
            leads: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            web_stats: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            marketing_campaigns: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            google_adwords: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            bings_adwords: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            houzz: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            facebook_instgram_ads: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],
            linkedins: [{
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],

            social_media_stats: [{
                social_media: '',
                title: '',
                jan: '',
                feb: '',
                mar: '',
                apr: '',
                may: '',
                june: '',
                july: '',
                aug: '',
                sep: '',
                oct: '',
                nov: '',
                decem: '',
                year: '',
            }],


        }
    },


    webState() {
        return [{
            title: 'Sessions/Website Traffic',
            jan: '3500',
            feb: '3800',
            mar: '3200',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'New Sessions',
            jan: '79.35%',
            feb: '79.94%',
            mar: '78.11%',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Pages per session',
            jan: '1.76',
            feb: '1.79',
            mar: '2.02',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Bounce Rate/Engagement rate as of Aug 2023*',
            jan: '53.61%',
            feb: '52.39%',
            mar: '61.04%',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Avg Session Duration',
            jan: '2.28',
            feb: '2.12',
            mar: '2.56',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Conversions',
            jan: '22',
            feb: '23',
            mar: '47',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Conversions Rate: Converstions/Sessions',
            jan: '0.63%',
            feb: '0.61%',
            mar: '1.47%',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        }]

    },


    marketingCampaigns() {
        return {
            google_adwords_2022: [
                {
                    title: 'Clicks',
                    jan: '708',
                    feb: '1000',
                    mar: '1200',
                    apr: '1600',
                    may: '1900',
                    june: '4700',
                    july: '1500',
                    aug: '1300',
                    sep: '1600',
                    oct: '1200',
                    nov: '1100',
                    decem: '1200',
                    year: '2022',
                },
                {
                    title: 'CTR',
                    jan: '0.40%',
                    feb: '0.80%',
                    mar: '0.70%',
                    apr: '1.10%',
                    may: '0.20%',
                    june: '1.20%',
                    july: '1.00%',
                    aug: '1.10%',
                    sep: '1.10%',
                    oct: '1.00%',
                    nov: '1.10%',
                    decem: '1.80%',
                    year: '2022',
                },
                {
                    title: 'Cost',
                    jan: '$859.74',
                    feb: '$745.35',
                    mar: '$877.70',
                    apr: '$878.00',
                    may: '$654.58',
                    june: '$777.01',
                    july: '$684.30',
                    aug: '$764.95',
                    sep: '$650.17',
                    oct: '$668.83',
                    nov: '$771.05',
                    decem: '$694.84',
                    year: '2022',
                },
                {
                    title: 'Conversions',
                    jan: '6',
                    feb: '8',
                    mar: '8',
                    apr: '8',
                    may: '4',
                    june: '7',
                    july: '4',
                    aug: '5',
                    sep: '7',
                    oct: '4',
                    nov: '7',
                    decem: '2',
                    year: '2022',
                },
                {
                    title: 'Cost/Click',
                    jan: '$1.21',
                    feb: '$0.72',
                    mar: '$0.74',
                    apr: '$0.57',
                    may: '$0.34',
                    june: '$0.16',
                    july: '$0.45',
                    aug: '$061',
                    sep: '$0.41',
                    oct: '$0.58',
                    nov: '$0.70',
                    decem: '$0.56',
                    year: '2022',
                },
                {
                    title: 'Cost/Conv',
                    jan: '$143.26',
                    feb: '$93.17',
                    mar: '$109.71',
                    apr: '$109.75',
                    may: '$163.64',
                    june: '$111.00',
                    july: '$171.08',
                    aug: '$152.99',
                    sep: '$92.88',
                    oct: '$167.21',
                    nov: '$110.15',
                    decem: '$347.42',
                    year: '2022',
                },
            ],


            google_adwords_2023: [
                {
                    title: 'Clicks',
                    jan: '1600',
                    feb: '1400',
                    mar: '1400',
                    apr: '1500',
                    may: '2300',
                    june: '3300',
                    july: '3800',
                    aug: '3500',
                    sep: '3100',
                    oct: '3300',
                    nov: '2800',
                    decem: '2600',
                    year: '2023',
                },
                {
                    title: 'CTR',
                    jan: '1.40%',
                    feb: '1.00%',
                    mar: '1.70%',
                    apr: '2.30%',
                    may: '2.10%',
                    june: '3.100%',
                    july: '4.10%',
                    aug: '2.50%',
                    sep: '1.90%',
                    oct: '3.50%',
                    nov: '3.20%',
                    decem: '2.00%',
                    year: '2023',
                },
                {
                    title: 'Cost',
                    jan: '$850.16',
                    feb: '$692.23',
                    mar: '$1200',
                    apr: '$961.25',
                    may: '$2650',
                    june: '$2560',
                    july: '$3100',
                    aug: '$3215',
                    sep: '$3210',
                    oct: '$3200',
                    nov: '$3210',
                    decem: '$2090',
                    year: '2023',
                },
                {
                    title: 'Conversions',
                    jan: '9',
                    feb: '4',
                    mar: '8',
                    apr: '8',
                    may: '7',
                    june: '12',
                    july: '8',
                    aug: '13',
                    sep: '19',
                    oct: '22',
                    nov: '18',
                    decem: '11',
                    year: '2023',
                },
                {
                    title: 'Cost/Click',
                    jan: '$0.52',
                    feb: '$0.50',
                    mar: '$0.88',
                    apr: '$0.66',
                    may: '$1.13',
                    june: '$0.78',
                    july: '$0.82',
                    aug: '$0.93',
                    sep: '$1.05',
                    oct: '$0.96',
                    nov: '$1.14',
                    decem: '$0.80',
                    year: '2023',
                },
                {
                    title: 'Cost/Conv',
                    jan: '$94.46',
                    feb: '$173.06',
                    mar: '$150.10',
                    apr: '$120.16',
                    may: '$378.24',
                    june: '$213.35',
                    july: '$387.50',
                    aug: '$247.31',
                    sep: '$170.74',
                    oct: '$145.45',
                    nov: '$178.08',
                    decem: '$190.00',
                    year: '2023',
                },
            ],


            google_adwords_2024: [
                {
                    title: 'Clicks',
                    jan: '3800',
                    feb: '3100',
                    mar: '1800',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: ' ',
                    year: '2024',
                },
                {
                    title: 'CTR',
                    jan: '2.60%',
                    feb: '1.70%',
                    mar: '3.50%',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: '',
                    year: '2024',
                },
                {
                    title: 'Cost',
                    jan: '$3220',
                    feb: '$3350',
                    mar: '$3190',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: ' ',
                    year: '2024',
                },
                {
                    title: 'Conversions',
                    jan: '19',
                    feb: '16',
                    mar: '41',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: ' ',
                    year: '2024',
                },
                {
                    title: 'Cost/Click',
                    jan: '$0.86',
                    feb: '$1.07',
                    mar: '$1.77',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: ' ',
                    year: '2024',
                },
                {
                    title: 'Cost/Conv',
                    jan: '$169.29',
                    feb: '$209.50',
                    mar: '$77.92',
                    apr: '',
                    may: '',
                    june: '',
                    july: '',
                    aug: '',
                    sep: '',
                    oct: '',
                    nov: '',
                    decem: ' ',
                    year: '2024',
                },
            ]
        }
    },


    bingAdwords2024() {
        return [{
            title: 'Click',
            jan: '3',
            feb: '194',
            mar: '214',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'CTR',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Cost',
            jan: '$9.90',
            feb: '$304.12',
            mar: '$304.24',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Conversions',
            jan: '0',
            feb: '7',
            mar: '1',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Cost/Click',
            jan: '$3.30',
            feb: '$1.57',
            mar: '$1.42',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        {
            title: 'Cost/Conv',
            jan: '$0.00',
            feb: '$43.45',
            mar: '$304.24',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '2024',
        },
        ]
    },


    houzz2023() {
        return [{
            title: 'Leads',
            jan: '',
            feb: '2',
            mar: '2',
            apr: '1',
            may: '5',
            june: '5',
            july: '3',
            aug: '3',
            sep: '3',
            oct: '5',
            nov: '0',
            decem: '2',
            year: '2023',
        },
        {
            title: 'Cost (one month was credited)',
            jan: '',
            feb: '$1077.00',
            mar: '$1077.00',
            apr: '$1077.00',
            may: '$1077.00',
            june: '$1077.00',
            july: '$1077.00',
            aug: '$1077.00',
            sep: '$1077.00',
            oct: '$1077.00',
            nov: '$1077.00',
            decem: '$1077.00',
            year: '2023',
        },
        {
            title: 'Cost/lead',
            jan: '',
            feb: '$538.50',
            mar: '$538.50',
            apr: '$1077.00',
            may: '$215.40',
            june: '$215.40',
            july: '$359.00',
            aug: '$359.00',
            sep: '$359.00',
            oct: '$215.40',
            nov: '$1077.00',
            decem: '$538.50',
            year: '202',
        },
        ]
    },


    facebook_instgram_ads2023() {
        return [{
            title: 'Clicks',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '190',
            july: '1104',
            aug: '3',
            sep: '179',
            oct: '1658',
            nov: '1345',
            decem: '',
            year: '',
        },
        {
            title: 'Cost',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '$145.43',
            july: '$150.32',
            aug: '$46.11',
            sep: '$211.48',
            oct: '$401.35',
            nov: '$428.32',
            decem: '',
            year: '',
        },
        {
            title: 'Cost per Click',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '$0.77',
            july: '$0.14',
            aug: '$15.37',
            sep: '$1.18',
            oct: '$0.24',
            nov: '$0.32',
            decem: '',
            year: '',
        },
        ]
    },


    facebook_instgram_ads2024() {
        return [{
            title: 'Clicks',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost per Click',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        ]
    },


    linkedin2023() {
        return [{
            title: 'Clicks',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost per Click',
            jan: '',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        ]
    },


    linkedin2023() {
        return [{
            title: 'Clicks',
            jan: '177',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost',
            jan: '$272.18',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        {
            title: 'Cost per Click',
            jan: '$1.54',
            feb: '',
            mar: '',
            apr: '',
            may: '',
            june: '',
            july: '',
            aug: '',
            sep: '',
            oct: '',
            nov: '',
            decem: '',
            year: '',
        },
        ]
    },


    social_media_stats_2022() {
        return [
            {
                instagram: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '3263',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],
        
        
                facebook: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '1100',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],


                linkedin: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '33',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],
            }
        ]
    },



    social_media_stats_2023() {
        return [
            {
                instagram: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '3406',
                        may: '3433',
                        june: '3496',
                        july: '3518',
                        aug: '3533',
                        sep: '3546',
                        oct: '3583',
                        nov: '3618',
                        decem: '3636',
                    },
                    {
                        title: 'Likes (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '31',
                        may: '36',
                        june: '30',
                        july: '16',
                        aug: '22',
                        sep: '18',
                        oct: '15',
                        nov: '18',
                        decem: '21',
                    },
                    {
                        title: 'Comments (last 10)',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '0-2',
                        may: '0-4',
                        june: '0-4',
                        july: '0-4',
                        aug: '2-4',
                        sep: '0-1',
                        oct: '0-1',
                        nov: '0-3',
                        decem: '0-3',
                    }
                ],
        
        
                facebook: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '1100',
                        may: '1100',
                        june: '1100',
                        july: '1100',
                        aug: '1100',
                        sep: '1100',
                        oct: '1100',
                        nov: '1100',
                        decem: '1100',
                    },
                    {
                        title: 'Likes',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '8',
                        may: '8',
                        june: '6 to 8',
                        july: '0-5',
                        aug: '0-5',
                        sep: '0-5',
                        oct: '0-5',
                        nov: '0-6',
                        decem: '9',
                    },
                    {
                        title: 'Comments',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                    }
                ],


                linkedin: [
                    {
                        title: 'Followers',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '299',
                        may: '414',
                        june: '583',
                        july: '647',
                        aug: '709',
                        sep: '751',
                        oct: '782',
                        nov: '800',
                        decem: '862',
                    },
                    {
                        title: 'Likes',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '12',
                        may: '14',
                        june: '5 to 10',
                        july: '10',
                        aug: '8',
                        sep: '9',
                        oct: '8',
                        nov: '6',
                        decem: '16',
                    },
                    {
                        title: 'Comments',
                        jan: '',
                        feb: '',
                        mar: '',
                        apr: '0',
                        may: '0-4',
                        june: '0 to 4',
                        july: '0 to 4',
                        aug: '0 to 4',
                        sep: '0-2',
                        oct: '0-2',
                        nov: '0-2',
                        decem: '0-2',
                    }
                ],
            }
        ]
    },


    social_media_stats_2024() {
        return [
            {
                instagram: [
                    {
                        title: 'Followers',
                        jan: '3678',
                        feb: '3753',
                        mar: '3823',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes (last 10)',
                        jan: '18',
                        feb: '26',
                        mar: '20',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments (last 10)',
                        jan: '0-3',
                        feb: '2',
                        mar: '0-2',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],
        
        
                facebook: [
                    {
                        title: 'Followers',
                        jan: '1200',
                        feb: '1220',
                        mar: '1228',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes',
                        jan: '2',
                        feb: '2',
                        mar: '3',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments',
                        jan: '0-1',
                        feb: '0-1',
                        mar: '0-2',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],


                linkedin: [
                    {
                        title: 'Followers',
                        jan: '907',
                        feb: '918',
                        mar: '966',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Likes',
                        jan: '13',
                        feb: '12',
                        mar: '10',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    },
                    {
                        title: 'Comments',
                        jan: '0-3',
                        feb: '0-3',
                        mar: '0-1',
                        apr: '',
                        may: '',
                        june: '',
                        july: '',
                        aug: '',
                        sep: '',
                        oct: '',
                        nov: '',
                        decem: '',
                        year: '',
                    }
                ],
            }
        ]
    },

}